<html>
<body>
<h2>Hello World! WELCOME TO MY JENKINS NEW-BUILD-PROJECT .THIS IS MY JENKINS FREESTYLE PROJECT </h2>
<h2>Hello World! WELCOME TO MY JENKINS NEW-BUILD-PROJECT .THIS IS MY JENKINS FREESTYLE PROJECT </h2>
</body>
</html>
